
DROP TABLE IF EXISTS 'EMPLOYEE_TABLE'
DROP TABLE IF EXISTS 'CUSTOMERS'
DROP TABLE IF EXISTS 'USER_TABLE'

CREATE TABLE CUSTOMERS
( customer_id number(10) NOT NULL,
  customer_name varchar2(50) NOT NULL,
  city varchar2(50)
);

CREATE TABLE EMPLOYEE_TABLE('ID' bigint(20) NOT NULL AUTO_INCREMENT,'ENAME' varchar(50) DEFAULT NULL,'SALARY' varchar(50) DEFAULT NULL);